/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.tnt.scp.scripteditor.panels;

import com.google.common.collect.Lists;
import org.openide.awt.Notification;
import org.openide.awt.NotificationDisplayer;
import org.openide.util.ImageUtilities;
import org.tnt.scp.common.generated.Script;

import javax.swing.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * @author sith
 */
public class AddCharacterPanel extends JPanel {

    private List<Script> scripts;
    private DefaultComboBoxModel comboBoxModel;

    /**
     * Creates new form AddCharacterPanel
     */
    public AddCharacterPanel(Collection<? extends Script> scripts) {
        this.scripts = Lists.newArrayList(scripts);

        comboBoxModel = new DefaultComboBoxModel();
        for (Script script : scripts) {
            comboBoxModel.addElement(script.getName());
        }
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scriptLabel = new javax.swing.JLabel();
        characterNameLabel = new javax.swing.JLabel();
        scriptsComboBox = new javax.swing.JComboBox();
        intiComboBox();
        characterNameTextField = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        descrtiptionTextArea = new javax.swing.JTextArea();

        org.openide.awt.Mnemonics.setLocalizedText(scriptLabel, org.openide.util.NbBundle.getMessage(AddCharacterPanel.class, "AddCharacterPanel.scriptLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(characterNameLabel, org.openide.util.NbBundle.getMessage(AddCharacterPanel.class, "AddCharacterPanel.characterNameLabel.text")); // NOI18N

        characterNameTextField.setText(org.openide.util.NbBundle.getMessage(AddCharacterPanel.class, "AddCharacterPanel.characterNameTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(descriptionLabel, org.openide.util.NbBundle.getMessage(AddCharacterPanel.class, "AddCharacterPanel.descriptionLabel.text")); // NOI18N

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        descrtiptionTextArea.setColumns(20);
        descrtiptionTextArea.setLineWrap(true);
        descrtiptionTextArea.setRows(5);
        scrollPane.setViewportView(descrtiptionTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(scriptLabel)
                                        .addComponent(characterNameLabel)
                                        .addComponent(descriptionLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(scriptsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(characterNameTextField)
                                        .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(scriptLabel)
                                        .addComponent(scriptsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(characterNameLabel)
                                        .addComponent(characterNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(descriptionLabel)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void intiComboBox() {
        scriptsComboBox.setModel(comboBoxModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel characterNameLabel;
    private javax.swing.JTextField characterNameTextField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descrtiptionTextArea;
    private javax.swing.JLabel scriptLabel;
    private javax.swing.JComboBox scriptsComboBox;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables


    public String getCharacterName() {
        return characterNameTextField.getText();
    }

    public String getDescription() {
        return descrtiptionTextArea.getText();
    }

    public Script getSelectedScript() {
        return scripts.get(scriptsComboBox.getSelectedIndex());
    }


}
